### PR TITLE
29-create-upload-files-api-endpoint BI

### PR DESCRIPTION
**Pull request by ghost**
29-create-upload-files-api-endpoint Done

### CODE REVIEW

**Review by nurmukhammadsunatullaev — CHANGES_REQUESTED** [review]
Dear Ilya, Could you create const variable for File Folder Path and I think we must not use full path.

**Review by dnovitsky — CHANGES_REQUESTED** [review]
Please rename 'DocumentController' into 'FilesController'.

**Comment by dnavitski** [comment]
@Hehalf
Please take the last code version from "dev" branch and merge it into your current branch. Currently, we have the merge conflict.

**Review by dnavitski — CHANGES_REQUESTED** [review]
@Hehalf 
Let review the code together.

**Pull request closed without merging**
