### PR TITLE
Docker added and Docker Compose tested

### PR DESCRIPTION
**Pull request by nurmukhammadsunatullaev**
Dear Mentors and friends!
Could you check docker in your laptop?

### CODE REVIEW

**Comment by nurmukhammadsunatullaev** [comment]
[Run SAPex application in Docker](https://trello.com/c/HJgb6HIk/26-run-sapex-application-in-docker)

**Review by ghost — APPROVED** [review]
Works fine

**Comment by dnovitsky** [comment]
@nurmukhammadsunatullaev 
please merge DEV into your branch

**Review by dnovitsky — CHANGES_REQUESTED** [review]
Please resolve conflicts with dev, all additional comments and verify with mentors

**Review by dnavitski — APPROVED** [review]
looks good

**Pull request merged**
